language: erlang
otp_release:
  - 19.2.3
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.4.2.zip
  - unzip -d elixir v1.4.2.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
